// 從 stores 導入介面，避免重複定義
import type { Caregiver } from '~/stores/caregivers'
import type { Booking } from '~/stores/bookings'

// 模擬資料
export const mockCaregivers: Caregiver[] = [
  {
    id: 'caregiver-001',
    name: '張美麗',
    avatar: 'https://i.pravatar.cc/150?img=1',
    gender: 'female',
    age: 35,
    rating: 4.8,
    reviews_count: 124,
    hourly_rate: 350,
    experience_years: 8,
    bio: '專業照護服務員，擁有8年以上照護經驗',
    description: '我是一位充滿愛心與耐心的專業看護師，專精於老人照護和失智症照護。我相信每位長者都值得受到最好的照顧。',
    skills: ['失智症照護', '復健協助', '傷口護理', '管灌餵食', '翻身拍背'],
    certifications: ['照顧服務員證照', '急救證照', '失智症照護專業訓練'],
    languages: ['中文', '台語', '英文'],
    service_areas: ['台北市', '新北市'],
    availability: {
      weekdays: true,
      weekends: true,
      nights: false,
      holidays: true,
    },
    is_available: true,
    total_service_hours: 12450,
    response_rate: 95,
    response_time: '1小時內',
    created_at: '2020-03-15',
    updated_at: '2024-01-10',
  },
  {
    id: 'caregiver-002',
    name: '王大明',
    avatar: 'https://i.pravatar.cc/150?img=8',
    gender: 'male',
    age: 42,
    rating: 4.9,
    reviews_count: 98,
    hourly_rate: 400,
    experience_years: 12,
    bio: '男性看護師，專精復健與行動輔助',
    description: '擁有物理治療背景，專門協助術後復健和行動不便的患者。提供專業且細心的照護服務。',
    skills: ['復健運動', '術後照護', '行動輔助', '肌力訓練', '關節活動'],
    certifications: ['照顧服務員證照', '物理治療助理證照', 'BLS基本生命支持術'],
    languages: ['中文', '台語'],
    service_areas: ['台北市', '桃園市'],
    availability: {
      weekdays: true,
      weekends: false,
      nights: false,
      holidays: false,
    },
    is_available: true,
    total_service_hours: 18200,
    response_rate: 98,
    response_time: '30分鐘內',
    created_at: '2018-06-20',
    updated_at: '2024-01-12',
  },
  {
    id: 'caregiver-003',
    name: '李秀英',
    avatar: 'https://i.pravatar.cc/150?img=5',
    gender: 'female',
    age: 38,
    rating: 4.7,
    reviews_count: 156,
    hourly_rate: 320,
    experience_years: 6,
    bio: '專業居家照護，擅長慢性病患者照護',
    description: '細心負責的看護師，擅長糖尿病、高血壓等慢性病患者的日常照護和健康管理。',
    skills: ['慢性病照護', '血糖監測', '藥物管理', '營養調配', '健康監測'],
    certifications: ['照顧服務員證照', '糖尿病衛教師'],
    languages: ['中文', '客語'],
    service_areas: ['新北市', '基隆市'],
    availability: {
      weekdays: true,
      weekends: true,
      nights: true,
      holidays: true,
    },
    is_available: true,
    total_service_hours: 9800,
    response_rate: 92,
    response_time: '2小時內',
    created_at: '2019-11-05',
    updated_at: '2024-01-11',
  },
  {
    id: 'caregiver-004',
    name: '陳淑芬',
    avatar: 'https://i.pravatar.cc/150?img=9',
    gender: 'female',
    age: 45,
    rating: 4.6,
    reviews_count: 67,
    hourly_rate: 380,
    experience_years: 10,
    bio: '安寧照護專家，提供臨終關懷服務',
    description: '擁有安寧照護專業訓練，能夠提供病患和家屬心理支持，讓生命最後一程充滿尊嚴。',
    skills: ['安寧照護', '疼痛管理', '心理支持', '家屬溝通', '臨終關懷'],
    certifications: ['照顧服務員證照', '安寧照護專業訓練', '心理諮商證照'],
    languages: ['中文', '台語', '日文'],
    service_areas: ['台北市'],
    availability: {
      weekdays: true,
      weekends: true,
      nights: true,
      holidays: true,
    },
    is_available: false,
    total_service_hours: 15600,
    response_rate: 88,
    response_time: '3小時內',
    created_at: '2017-02-18',
    updated_at: '2024-01-09',
  },
  {
    id: 'caregiver-005',
    name: '林志成',
    avatar: 'https://i.pravatar.cc/150?img=12',
    gender: 'male',
    age: 28,
    rating: 4.5,
    reviews_count: 43,
    hourly_rate: 300,
    experience_years: 3,
    bio: '年輕有活力，專注兒童特殊照護',
    description: '專門照護發展遲緩和特殊需求兒童，有耐心且充滿愛心，深受家長信任。',
    skills: ['兒童照護', '特殊教育', '復健遊戲', '行為管理', '感覺統合'],
    certifications: ['照顧服務員證照', '兒童發展評估訓練'],
    languages: ['中文', '英文'],
    service_areas: ['台北市', '新竹市'],
    availability: {
      weekdays: true,
      weekends: true,
      nights: false,
      holidays: true,
    },
    is_available: true,
    total_service_hours: 4200,
    response_rate: 90,
    response_time: '1小時內',
    created_at: '2021-04-10',
    updated_at: '2024-01-13',
  },
  {
    id: 'caregiver-006',
    name: '黃雅婷',
    avatar: 'https://i.pravatar.cc/150?img=20',
    gender: 'female',
    age: 33,
    rating: 4.8,
    reviews_count: 89,
    hourly_rate: 360,
    experience_years: 7,
    bio: '專業產後護理，新生兒照護專家',
    description: '護理系畢業，專精產後護理和新生兒照護，協助新手媽媽順利度過產後恢復期。',
    skills: ['產後護理', '新生兒照護', '母乳哺育', '嬰兒按摩', '產後運動'],
    certifications: ['護理師證照', '國際泌乳顧問', '嬰兒按摩指導員'],
    languages: ['中文', '英文'],
    service_areas: ['台北市', '新北市'],
    availability: {
      weekdays: true,
      weekends: false,
      nights: true,
      holidays: false,
    },
    is_available: true,
    total_service_hours: 8900,
    response_rate: 96,
    response_time: '30分鐘內',
    created_at: '2018-09-22',
    updated_at: '2024-01-14',
  },
  {
    id: 'caregiver-007',
    name: '趙文華',
    avatar: 'https://i.pravatar.cc/150?img=15',
    gender: 'male',
    age: 48,
    rating: 4.7,
    reviews_count: 112,
    hourly_rate: 330,
    experience_years: 15,
    bio: '資深看護師，擅長重症照護',
    description: '在醫院重症病房工作多年，對重症患者照護有豐富經驗，能處理各種緊急狀況。',
    skills: ['重症照護', '呼吸器照護', '傷口護理', '管路護理', '緊急處理'],
    certifications: ['護理師證照', 'ACLS高級心臟救命術', '重症照護證照'],
    languages: ['中文', '台語', '客語'],
    service_areas: ['台北市', '新北市', '桃園市'],
    availability: {
      weekdays: true,
      weekends: true,
      nights: true,
      holidays: true,
    },
    is_available: true,
    total_service_hours: 22800,
    response_rate: 94,
    response_time: '45分鐘內',
    created_at: '2015-08-10',
    updated_at: '2024-01-15',
  },
  {
    id: 'caregiver-008',
    name: '許玉珍',
    avatar: 'https://i.pravatar.cc/150?img=23',
    gender: 'female',
    age: 52,
    rating: 4.9,
    reviews_count: 203,
    hourly_rate: 370,
    experience_years: 20,
    bio: '資深護理師，專精老人照護',
    description: '二十年護理經驗，專門照護高齡長者，對失智症、帕金森氏症等老年疾病有深入了解。',
    skills: ['老人照護', '失智症照護', '帕金森氏症照護', '跌倒預防', '認知訓練'],
    certifications: ['護理師證照', '老人照護專業證照', '失智症照護證照'],
    languages: ['中文', '台語', '日文', '英文'],
    service_areas: ['台北市', '新北市'],
    availability: {
      weekdays: true,
      weekends: true,
      nights: false,
      holidays: true,
    },
    is_available: true,
    total_service_hours: 31200,
    response_rate: 97,
    response_time: '30分鐘內',
    created_at: '2012-03-25',
    updated_at: '2024-01-16',
  },
]

// 地區選項
export const locationOptions = [
  '台北市',
  '新北市',
  '桃園市',
  '台中市',
  '台南市',
  '高雄市',
  '基隆市',
  '新竹市',
]

// 技能選項
export const skillOptions = [
  '失智症照護',
  '復健協助',
  '傷口護理',
  '管灌餵食',
  '翻身拍背',
  '慢性病照護',
  '安寧照護',
  '兒童照護',
  '產後護理',
  '新生兒照護',
  '重症照護',
  '老人照護',
]

// 經驗年數選項
export const experienceOptions = [
  { label: '不限', value: 'all' },
  { label: '1-3年', value: '1-3' },
  { label: '3-5年', value: '3-5' },
  { label: '5-10年', value: '5-10' },
  { label: '10年以上', value: '10+' },
]

// 價格範圍建議
export const priceRanges = [
  { label: '不限', min: null, max: null },
  { label: '$300以下', min: null, max: 300 },
  { label: '$300-350', min: 300, max: 350 },
  { label: '$350-400', min: 350, max: 400 },
  { label: '$400以上', min: 400, max: null },
]

// 語言選項
export const languageOptions = [
  '中文',
  '台語',
  '客語',
  '英文',
  '日文',
]

// 證照選項
export const certificationOptions = [
  '照顧服務員證照',
  '護理師證照',
  '急救證照',
  '失智症照護專業訓練',
  '物理治療助理證照',
  'BLS基本生命支持術',
  'ACLS高級心臟救命術',
  '重症照護證照',
  '老人照護專業證照',
]

// 性別選項
export const genderOptions = [
  { label: '不限', value: 'all' },
  { label: '男性', value: 'male' },
  { label: '女性', value: 'female' },
]

// 可用時段選項
export const availabilityOptions = [
  { label: '平日', value: 'weekdays' },
  { label: '週末', value: 'weekends' },
  { label: '夜間', value: 'nights' },
  { label: '假日', value: 'holidays' },
]